/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScribeRouteImport } from './routes/scribe'
import { Route as ClinicalRouteImport } from './routes/clinical'
import { Route as IndexRouteImport } from './routes/index'

const ScribeRoute = ScribeRouteImport.update({
  id: '/scribe',
  path: '/scribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalRoute = ClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinical': typeof ClinicalRoute
  '/scribe': typeof ScribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinical': typeof ClinicalRoute
  '/scribe': typeof ScribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinical': typeof ClinicalRoute
  '/scribe': typeof ScribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clinical' | '/scribe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clinical' | '/scribe'
  id: '__root__' | '/' | '/clinical' | '/scribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicalRoute: typeof ClinicalRoute
  ScribeRoute: typeof ScribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scribe': {
      id: '/scribe'
      path: '/scribe'
      fullPath: '/scribe'
      preLoaderRoute: typeof ScribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical': {
      id: '/clinical'
      path: '/clinical'
      fullPath: '/clinical'
      preLoaderRoute: typeof ClinicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicalRoute: ClinicalRoute,
  ScribeRoute: ScribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
